# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: introspectDaily
brief-intro: Embedded Engineer & NLP Engineer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://introspectdaily.github.io/" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: none
facebook_username: none
github_username:  introspectDaily
email: 1795973398@qq.com
weibo_username: none
zhihu_username: none
linkedIn_username: none
dribbble_username:

description_footer: 本站记录我前端之旅的沿途风景！

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: #hygblog
disqus_shortname: https-introspectdaily-github-io

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 1186a6a5d9f49a9421f2ef22794f8bb0
google_analytics_id: G-2H2YE9XG4J # google 分析追踪id

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate
